spring:
  profiles:
    active: test
  devtools:
    restart:
      enabled: true
mybatis:
  type-aliases-package: com.dao
  mapper-locations: classpath:mapper/*.xml


fdfs:
  http:
    storage-addr: http://192.168.174.128:8888/group1/

